services:
  - type: web
<<<<<<< HEAD
    name: mirudula-health-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
=======
<<<<<<< HEAD
    name: diabetes-predictor-meal
=======
    name: diabetes-predictor
>>>>>>> e3f99357a60b8229cd3166b4c3a70118ab3fd085
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
>>>>>>> c5edf7ec071f4b8303d7e1e094805c44a440ef82
